package net.morthen.resourcelibrary.modifier.loot_tables;

import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.storage.loot.LootTable;
import net.morthen.resourcelibrary.LibConstants;

public class ChestLootTables {
    public static final ResourceKey<LootTable> ABANDONED_MINESHAFT = LibConstants.createLootTableKey("chests/abandoned_mineshaft");
    public static final ResourceKey<LootTable> ANCIENT_CITY = LibConstants.createLootTableKey("chests/ancient_city");
    public static final ResourceKey<LootTable> ANCIENT_CITY_ICE_BOX = LibConstants.createLootTableKey("chests/ancient_city_ice_box");
    public static final ResourceKey<LootTable> BASTION_BRIDGE = LibConstants.createLootTableKey("chests/bastion_bridge");
    public static final ResourceKey<LootTable> BASTION_HOGLIN_STABLE = LibConstants.createLootTableKey("chests/bastion_hoglin_stable");
    public static final ResourceKey<LootTable> BASTION_OTHER = LibConstants.createLootTableKey("chests/bastion_other");
    public static final ResourceKey<LootTable> BASTION_TREASURE = LibConstants.createLootTableKey("chests/bastion_treasure");
    public static final ResourceKey<LootTable> BURIED_TREASURE = LibConstants.createLootTableKey("chests/buried_treasure");
    public static final ResourceKey<LootTable> DESERT_PYRAMID = LibConstants.createLootTableKey("chests/desert_pyramid");
    public static final ResourceKey<LootTable> END_CITY_TREASURE = LibConstants.createLootTableKey("chests/end_city_treasure");
    public static final ResourceKey<LootTable> IGLOO_CHEST = LibConstants.createLootTableKey("chests/igloo_chest");
    public static final ResourceKey<LootTable> JUNGLE_TEMPLE = LibConstants.createLootTableKey("chests/jungle_temple");
    public static final ResourceKey<LootTable> JUNGLE_TEMPLE_DISPENSER = LibConstants.createLootTableKey("chests/jungle_temple_dispenser");
    public static final ResourceKey<LootTable> NETHER_BRIDGE = LibConstants.createLootTableKey("chests/nether_bridge");
    public static final ResourceKey<LootTable> PILLAGER_OUTPOST = LibConstants.createLootTableKey("chests/pillager_outpost");
    public static final ResourceKey<LootTable> RUINED_PORTAL = LibConstants.createLootTableKey("chests/ruined_portal");
    public static final ResourceKey<LootTable> SHIPWRECK_MAP = LibConstants.createLootTableKey("chests/shipwreck_map");
    public static final ResourceKey<LootTable> SHIPWRECK_SUPPLY = LibConstants.createLootTableKey("chests/shipwreck_supply");
    public static final ResourceKey<LootTable> SHIPWRECK_TREASURE = LibConstants.createLootTableKey("chests/shipwreck_treasure");
    public static final ResourceKey<LootTable> SIMPLE_DUNGEON = LibConstants.createLootTableKey("chests/simple_dungeon");
    public static final ResourceKey<LootTable> SPAWN_BONUS_CHEST = LibConstants.createLootTableKey("chests/spawn_bonus_chest");
    public static final ResourceKey<LootTable> STRONGHOLD_CORRIDOR = LibConstants.createLootTableKey("chests/stronghold_corridor");
    public static final ResourceKey<LootTable> STRONGHOLD_CROSSING = LibConstants.createLootTableKey("chests/stronghold_crossing");
    public static final ResourceKey<LootTable> STRONGHOLD_LIBRARY = LibConstants.createLootTableKey("chests/stronghold_library");
    public static final ResourceKey<LootTable> UNDERWATER_RUIN_BIG = LibConstants.createLootTableKey("chests/underwater_ruin_big");
    public static final ResourceKey<LootTable> UNDERWATER_RUIN_SMALL = LibConstants.createLootTableKey("chests/underwater_ruin_small");
    public static final ResourceKey<LootTable> VILLAGE_ARMORER = LibConstants.createLootTableKey("chests/village/village_armorer");
    public static final ResourceKey<LootTable> VILLAGE_BUTCHER = LibConstants.createLootTableKey("chests/village/village_butcher");
    public static final ResourceKey<LootTable> VILLAGE_CARTOGRAPHER = LibConstants.createLootTableKey("chests/village/village_cartographer");
    public static final ResourceKey<LootTable> VILLAGE_DESERT_HOUSE = LibConstants.createLootTableKey("chests/village/village_desert_house");
    public static final ResourceKey<LootTable> VILLAGE_FISHER = LibConstants.createLootTableKey("chests/village/village_fisher");
    public static final ResourceKey<LootTable> VILLAGE_FLETCHER = LibConstants.createLootTableKey("chests/village/village_fletcher");
    public static final ResourceKey<LootTable> VILLAGE_MASON = LibConstants.createLootTableKey("chests/village/village_mason");
    public static final ResourceKey<LootTable> VILLAGE_PLAINS_HOUSE = LibConstants.createLootTableKey("chests/village/village_plains_house");
    public static final ResourceKey<LootTable> VILLAGE_SAVANNA_HOUSE = LibConstants.createLootTableKey("chests/village/village_savanna_house");
    public static final ResourceKey<LootTable> VILLAGE_SHEPHERD = LibConstants.createLootTableKey("chests/village/village_shepherd");
    public static final ResourceKey<LootTable> VILLAGE_SNOWY_HOUSE = LibConstants.createLootTableKey("chests/village/village_snowy_house");
    public static final ResourceKey<LootTable> VILLAGE_TAIGA_HOUSE = LibConstants.createLootTableKey("chests/village/village_taiga_house");
    public static final ResourceKey<LootTable> VILLAGE_TANNERY = LibConstants.createLootTableKey("chests/village/village_tannery");
    public static final ResourceKey<LootTable> VILLAGE_TEMPLE = LibConstants.createLootTableKey("chests/village/village_temple");
    public static final ResourceKey<LootTable> VILLAGE_TOOLSMITH = LibConstants.createLootTableKey("chests/village/village_toolsmith");
    public static final ResourceKey<LootTable> VILLAGE_WEAPONSMITH = LibConstants.createLootTableKey("chests/village/village_weaponsmith");
    public static final ResourceKey<LootTable> WOODLAND_MANSION = LibConstants.createLootTableKey("chests/woodland_mansion");
}
