plugins {
    id 'idea'
    id 'java-library'
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT' apply false
    id 'net.minecraftforge.gradle' version '[7.0.29,8.0)' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
    id 'me.modmuss50.mod-publish-plugin' version '2.0.1' apply false
}