org.gradle.jvmargs=-Xmx8192M
org.gradle.daemon=false

# Project
version=0.0.1
group=net.xstopho.resource_library
java_version=21
modrinth_id=XLhounCW
curseforge_id=975803

# Common
mod_name=Resource Library
mod_author=xStopho
mod_id=resourcelibrary
mod_license=MIT
mod_credits=
mod_description=Library with common abstractions for my Mods