package net.xstopho.resourcelibrary.modifier.loot_tables;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.storage.loot.LootTable;

public class EntityLootTables {
    public static final ResourceKey<LootTable> ALLAY = createKey("entities/allay");
    public static final ResourceKey<LootTable> ARMADILLO = createKey("entities/armadillo");
    public static final ResourceKey<LootTable> ARMOR_STAND = createKey("entities/armor_stand");
    public static final ResourceKey<LootTable> AXOLOTL = createKey("entities/axolotl");
    public static final ResourceKey<LootTable> BAT = createKey("entities/bat");
    public static final ResourceKey<LootTable> BEE = createKey("entities/bee");
    public static final ResourceKey<LootTable> BLAZE = createKey("entities/blaze");
    public static final ResourceKey<LootTable> BOGGED = createKey("entities/bogged");
    public static final ResourceKey<LootTable> BREEZE = createKey("entities/breeze");
    public static final ResourceKey<LootTable> CAMEL = createKey("entities/camel");
    public static final ResourceKey<LootTable> CAT = createKey("entities/cat");
    public static final ResourceKey<LootTable> CAVE_SPIDER = createKey("entities/cave_spider");
    public static final ResourceKey<LootTable> CHICKEN = createKey("entities/chicken");
    public static final ResourceKey<LootTable> COD = createKey("entities/cod");
    public static final ResourceKey<LootTable> COW = createKey("entities/cow");
    public static final ResourceKey<LootTable> CREAKING = createKey("entities/creaking");
    public static final ResourceKey<LootTable> CREAKING_TRANSIENT = createKey("entities/creaking_transient");
    public static final ResourceKey<LootTable> CREEPER = createKey("entities/creeper");
    public static final ResourceKey<LootTable> DOLPHIN = createKey("entities/dolphin");
    public static final ResourceKey<LootTable> DONKEY = createKey("entities/donkey");
    public static final ResourceKey<LootTable> DROWNED = createKey("entities/drowned");
    public static final ResourceKey<LootTable> ELDER_GUARDIAN = createKey("entities/elder_guardian");
    public static final ResourceKey<LootTable> ENDER_DRAGON = createKey("entities/ender_dragon");
    public static final ResourceKey<LootTable> ENDERMAN = createKey("entities/enderman");
    public static final ResourceKey<LootTable> ENDERMITE = createKey("entities/endermite");
    public static final ResourceKey<LootTable> EVOKER = createKey("entities/evoker");
    public static final ResourceKey<LootTable> FOX = createKey("entities/fox");
    public static final ResourceKey<LootTable> FROG = createKey("entities/frog");
    public static final ResourceKey<LootTable> GHAST = createKey("entities/ghast");
    public static final ResourceKey<LootTable> GIANT = createKey("entities/giant");
    public static final ResourceKey<LootTable> GLOW_SQUID = createKey("entities/glow_squid");
    public static final ResourceKey<LootTable> GOAT = createKey("entities/goat");
    public static final ResourceKey<LootTable> GUARDIAN = createKey("entities/guardian");
    public static final ResourceKey<LootTable> HOGLIN = createKey("entities/hoglin");
    public static final ResourceKey<LootTable> HORSE = createKey("entities/horse");
    public static final ResourceKey<LootTable> HUSK = createKey("entities/husk");
    public static final ResourceKey<LootTable> ILLUSIONER = createKey("entities/illusioner");
    public static final ResourceKey<LootTable> IRON_GOLEM = createKey("entities/iron_golem");
    public static final ResourceKey<LootTable> LLAMA = createKey("entities/llama");
    public static final ResourceKey<LootTable> MAGMA_CUBE = createKey("entities/magma_cube");
    public static final ResourceKey<LootTable> MOOSHROOM = createKey("entities/mooshroom");
    public static final ResourceKey<LootTable> MULE = createKey("entities/mule");
    public static final ResourceKey<LootTable> OCELOT = createKey("entities/ocelot");
    public static final ResourceKey<LootTable> PANDA = createKey("entities/panda");
    public static final ResourceKey<LootTable> PARROT = createKey("entities/parrot");
    public static final ResourceKey<LootTable> PHANTOM = createKey("entities/phantom");
    public static final ResourceKey<LootTable> PIG = createKey("entities/pig");
    public static final ResourceKey<LootTable> PIGLIN = createKey("entities/piglin");
    public static final ResourceKey<LootTable> PIGLIN_BRUTE = createKey("entities/piglin_brute");
    public static final ResourceKey<LootTable> PILLAGER = createKey("entities/pillager");
    public static final ResourceKey<LootTable> PLAYER = createKey("entities/player");
    public static final ResourceKey<LootTable> POLAR_BEAR = createKey("entities/polar_bear");
    public static final ResourceKey<LootTable> PUFFERFISH = createKey("entities/pufferfish");
    public static final ResourceKey<LootTable> RABBIT = createKey("entities/rabbit");
    public static final ResourceKey<LootTable> RAVAGER = createKey("entities/ravager");
    public static final ResourceKey<LootTable> SALMON = createKey("entities/salmon");
    public static final ResourceKey<LootTable> SHEEP = createKey("entities/sheep");
    public static final ResourceKey<LootTable> SHEEP_BLACK = createKey("entities/sheep/black");
    public static final ResourceKey<LootTable> SHEEP_BLUE = createKey("entities/sheep/blue");
    public static final ResourceKey<LootTable> SHEEP_BROWN = createKey("entities/sheep/brown");
    public static final ResourceKey<LootTable> SHEEP_CYAN = createKey("entities/sheep/cyan");
    public static final ResourceKey<LootTable> SHEEP_GRAY = createKey("entities/sheep/gray");
    public static final ResourceKey<LootTable> SHEEP_GREEN = createKey("entities/sheep/green");
    public static final ResourceKey<LootTable> SHEEP_LIGHT_BLUE = createKey("entities/sheep/light_blue");
    public static final ResourceKey<LootTable> SHEEP_LIGHT_GRAY = createKey("entities/sheep/light_gray");
    public static final ResourceKey<LootTable> SHEEP_LIME = createKey("entities/sheep/lime");
    public static final ResourceKey<LootTable> SHEEP_MAGENTA = createKey("entities/sheep/magenta");
    public static final ResourceKey<LootTable> SHEEP_ORANGE = createKey("entities/sheep/orange");
    public static final ResourceKey<LootTable> SHEEP_PINK = createKey("entities/sheep/pink");
    public static final ResourceKey<LootTable> SHEEP_PURPLE = createKey("entities/sheep/purple");
    public static final ResourceKey<LootTable> SHEEP_RED = createKey("entities/sheep/red");
    public static final ResourceKey<LootTable> SHEEP_WHITE = createKey("entities/sheep/white");
    public static final ResourceKey<LootTable> SHEEP_YELLOW = createKey("entities/sheep/yellow");
    public static final ResourceKey<LootTable> SHULKER = createKey("entities/shulker");
    public static final ResourceKey<LootTable> SILVERFISH = createKey("entities/silverfish");
    public static final ResourceKey<LootTable> SKELETON = createKey("entities/skeleton");
    public static final ResourceKey<LootTable> SKELETON_HORSE = createKey("entities/skeleton_horse");
    public static final ResourceKey<LootTable> SLIME = createKey("entities/slime");
    public static final ResourceKey<LootTable> SNIFFER = createKey("entities/sniffer");
    public static final ResourceKey<LootTable> SNOW_GOLEM = createKey("entities/snow_golem");
    public static final ResourceKey<LootTable> SPIDER = createKey("entities/spider");
    public static final ResourceKey<LootTable> SQUID = createKey("entities/squid");
    public static final ResourceKey<LootTable> STRAY = createKey("entities/stray");
    public static final ResourceKey<LootTable> STRIDER = createKey("entities/strider");
    public static final ResourceKey<LootTable> TADPOLE = createKey("entities/tadpole");
    public static final ResourceKey<LootTable> TRADER_LLAMA = createKey("entities/trader_llama");
    public static final ResourceKey<LootTable> TROPICAL_FISH = createKey("entities/tropical_fish");
    public static final ResourceKey<LootTable> TURTLE = createKey("entities/turtle");
    public static final ResourceKey<LootTable> VEX = createKey("entities/vex");
    public static final ResourceKey<LootTable> VILLAGER = createKey("entities/villager");
    public static final ResourceKey<LootTable> VINDICATOR = createKey("entities/vindicator");
    public static final ResourceKey<LootTable> WANDERING_TRADER = createKey("entities/wandering_trader");
    public static final ResourceKey<LootTable> WARDEN = createKey("entities/warden");
    public static final ResourceKey<LootTable> WITCH = createKey("entities/witch");
    public static final ResourceKey<LootTable> WITHER = createKey("entities/wither");
    public static final ResourceKey<LootTable> WITHER_SKELETON = createKey("entities/wither_skeleton");
    public static final ResourceKey<LootTable> WOLF = createKey("entities/wolf");
    public static final ResourceKey<LootTable> ZOGLIN = createKey("entities/zoglin");
    public static final ResourceKey<LootTable> ZOMBIE = createKey("entities/zombie");
    public static final ResourceKey<LootTable> ZOMBIE_HORSE = createKey("entities/zombie_horse");
    public static final ResourceKey<LootTable> ZOMBIE_VILLAGER = createKey("entities/zombie_villager");
    public static final ResourceKey<LootTable> ZOMBIFIED_PIGLIN = createKey("entities/zombified_piglin");

    public static ResourceKey<LootTable> createKey(String id) {
        return ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.withDefaultNamespace(id));
    }
}
