modLoader = "javafml"
loaderVersion = "[51,)"
license = "MIT"

[[mods]]
    modId = "resourcelibrary_test"
    version = "1.0-TEST"
    displayName = "Resource Library Test"
    logoFile = "icon_forge.png"
    authors = "xStopho"
    description = "Testmod for Resource Library"

[[dependencies.resourcelibrary_test]]
    modId = "forge"
    mandatory = true
    versionRange = "[51,)"
    ordering = "NONE"
    side = "BOTH"