plugins {
    id 'ml-loader'
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin'
}

sourceSets {
    testmod {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

configurations {
    includeLibs
}

dependencies {
    testmodImplementation sourceSets.main.output

    testmodImplementation project(':common').sourceSets.testmod.output
}

neoForge {
    version = neoforge_version

    parchment {
        minecraftVersion = parchment_mc_version
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enableGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }

        testClient {
            client()
            sourceSet = sourceSets.testmod
            gameDirectory = file("../common/runs/client")
        }
    }
    mods {
        "${mod_id}" { sourceSet sourceSets.main }
        "${mod_id}_test" { sourceSet sourceSets.testmod }
    }
}

compileTestmodJava {
    source(project(':common').sourceSets.testmod.allSource)
}
processTestmodResources {
    from project(':common').sourceSets.testmod.resources
    from file('src/generated/resources')
}

publishMods {
    file = jar.archiveFile
    modLoaders.add("neoforge")
}