plugins {
    id 'ml-loader'
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin'
}

sourceSets {
    testmod {
        runtimeClasspath += main.runtimeClasspath;
        compileClasspath += main.compileClasspath;
        resources { srcDir 'src/testmod/generated' }
    }
}

dependencies {
    testmodImplementation sourceSets.main.output
}

neoForge {
    version = neoforge_version

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enableGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }

        testClient {
            client()
            sourceSet = sourceSets.testmod
            gameDirectory = project.file("runs/client")
        }

        testDatagen {
            data()
            sourceSet = sourceSets.testmod
            gameDirectory = project.file("runs/data")
            programArguments.addAll '--mod', 'resourcelibrary_test', '--all', '--output', file('src/testmod/generated/').getAbsolutePath(), '--existing', file('src/testmod/resources/').getAbsolutePath()
        }
    }
    mods {
        "${mod_id}" { sourceSet sourceSets.main }
        "${mod_id}_test" { sourceSet sourceSets.testmod }
    }
}

publishMods {
    file = jar.archiveFile
    modLoaders.add("neoforge")
}