plugins {
    id 'ml-common'
    id 'fabric-loom'
}

def directory = project.projectDir.parent.split("\\\\").last()

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    compileOnly(project(":${directory}:common"))
    testmodImplementation project(':snapshot:common').sourceSets.testmod.output

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}+1.21.5"
}

loom {
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }

    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) accessWidenerPath.set(aw)

    runs {
        client {
            client()
            source sourceSets.testmod
            setConfigName("Fabric Test Client")
            ideConfigGenerated(true)
            programArgs('--username', 'Dev')
            runDir("runs/client")
        }
    }
}

tasks.named('compileJava', JavaCompile) {
    source(project(":${directory}:common").sourceSets.main.allSource)
}

tasks.named('javadoc', Javadoc) {
    source(project(":${directory}:common").sourceSets.main.allJava)
}

processResources {
    from project(":${directory}:common").sourceSets.main.resources
}
